### ISSUE TITLE
Deployed on Heroku, "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by mkhorton** [jollygoodcode/dasherize#63]
First off, thanks for making this! It looks really cool :)

Trying to deploy my own instance so I can customize the theme etc... followed the instructions, application deployed successfully on Heroku, environment variables set according to instructions including github client ID and secret. However, I see this page:

<img width="1402" alt="dasherize" src="https://user-images.githubusercontent.com/2976580/31521605-035ab32e-af5f-11e7-88dc-d12755ce5afe.png">

Do you have any tips on how to debug? Thank you.

(Build log also attached if it helps: [buildlog.txt](https://github.com/jollygoodcode/dasherize/files/1380848/buildlog.txt))

**Comment by JuanitoFatas** [comment]
Hi there, look into [application logs](https://devcenter.heroku.com/articles/logging) could find the cause. And make sure [ENVs are set](https://github.com/jollygoodcode/dasherize#env). :)

**Comment by mkhorton** [comment]
Hi @JuanitoFatas, thanks for the advice -- the ENVs `WWW_HOSTNAME`, `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` seem like they're set correctly.

Logs say this:

```
2017-10-13T17:15:20.155383+00:00 app[web.1]: Processing by HomeController#index as HTML
2017-10-13T17:15:20.176792+00:00 app[web.1]: Completed 500 Internal Server Error in 21ms (ActiveRecord: 2.4ms)
2017-10-13T17:15:20.179601+00:00 app[web.1]: 
2017-10-13T17:15:20.179603+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "projects" does not exist
2017-10-13T17:15:20.179603+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"projects"'::regclass
2017-10-13T17:15:20.179604+00:00 app[web.1]:                                           ^
2017-10-13T17:15:20.179605+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-10-13T17:15:20.179605+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2017-10-13T17:15:20.179606+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-10-13T17:15:20.179607+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-10-13T17:15:20.179607+00:00 app[web.1]:                WHERE a.attrelid = '"projects"'::regclass
2017-10-13T17:15:20.179607+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-10-13T17:15:20.179608+00:00 app[web.1]:                ORDER BY a.attnum
2017-10-13T17:15:20.179608+00:00 app[web.1]: ):
2017-10-13T17:15:20.179609+00:00 app[web.1]:   app/controllers/home_controller.rb:9:in `block in index'
2017-10-13T17:15:20.179609+00:00 app[web.1]:   app/controllers/home_controller.rb:7:in `index'
2017-10-13T17:15:20.179609+00:00 app[web.1]: 
2017-10-13T17:15:20.179610+00:00 app[web.1]: 
2017-10-13T17:15:20.181385+00:00 app[web.1]: Processing by ErrorsController#show as HTML
2017-10-13T17:15:20.181432+00:00 app[web.1]:   Parameters: {"code"=>"500"}
```

**Comment by mkhorton** [comment]
By the way, why does Dasherize require such broad OAUTH permissions? Write access, including to private repos?

**Comment by winston** [comment]
@mkhorton Hmm. Is that a DB migration issue?

> broad OAUTH permissions

That's GitHub's limitation. If you want to read Private repos, it's either all or none. :(
